### PR TITLE
Support for ES 7.x

### PR DESCRIPTION
**Pull request by shiveshsky**
Hi Team,
I have made some changes to support new ES versions.
I have attached the updated jar along. However, docker image is not updated.

### CODE REVIEW

**Comment by ozlerhakan** [comment]
Hi @shiveshsky , thank you for your changes! This needs a bit updates to work it correctly

**Comment by shiveshsky** [comment]
Hi @ozlerhakan  can you please guide me so that I can make it work out.
Thanks

**Comment by ozlerhakan** [comment]
Hi @shiveshsky , I'm sorry for being unresponsive. Do you still want this PR ?

**Comment by christopher** [comment]
@ozlerhakan , Yes. Please make mongolastic work with current version (7.7.1) of ES.

**Comment by shiveshsky** [comment]
@christopher I have a forked version working you can try that https://github.com/shiveshsky/mongolastic

**Comment by shiveshsky** [comment]
@ozlerhakan I think we can close
Thanks

**Comment by ozlerhakan** [comment]
ah great @shiveshsky! , create a new PR so that we can merge your changes as well

**Pull request closed without merging**
